//! HaInviter — guest invitations and RSVP tracking.
//!
//! One binary serves three things: the admin panel, the per-guest invitation
//! pages, and the WASM bundle that drives both. The same crate is compiled twice
//! — once for `wasm32-unknown-unknown` (`--features web`) and once natively
//! (`--features server`) — so the page components and the DTOs are shared and can
//! never drift apart.

mod api;
mod types;
mod ui;

#[cfg(feature = "server")]
mod audit;
#[cfg(feature = "server")]
mod auth;
#[cfg(feature = "server")]
mod db;
#[cfg(feature = "server")]
mod export;

#[cfg(all(test, feature = "server"))]
mod tests;

use dioxus::prelude::*;
use ui::{AdminEvent, AdminEvents, Home, Invite, NotFound};

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

/// Every page in the application.
///
/// Both admin routes carry the admin token in the path: there is no session, so
/// the URL *is* the credential and must travel with every navigation.
#[derive(Clone, Debug, PartialEq, Routable)]
pub enum Route {
    #[route("/")]
    Home {},

    /// A guest's personal invitation.
    #[route("/i/:token")]
    Invite { token: String },

    #[route("/admin/:token")]
    AdminEvents { token: String },

    #[route("/admin/:token/e/:event_id")]
    AdminEvent { token: String, event_id: i64 },

    #[route("/:..segments")]
    NotFound { segments: Vec<String> },
}

/// Root component: global assets plus the router.
#[component]
fn App() -> Element {
    rsx! {
        document::Link { rel: "icon", href: asset!("/assets/favicon.svg") }
        document::Stylesheet { href: asset!("/assets/material.css") }
        document::Stylesheet { href: asset!("/assets/app.css") }
        Router::<Route> {}
    }
}

// ---------------------------------------------------------------------------
// Server entry point
// ---------------------------------------------------------------------------

#[cfg(feature = "server")]
#[tokio::main]
async fn main() {
    use axum::routing::get;
    use dioxus::server::{DioxusRouterExt, ServeConfig};

    let data = db::data_dir();
    println!("hainviter: data directory is {}", data.display());
    if let Err(e) = std::fs::create_dir_all(db::uploads_dir()) {
        // Not fatal: only cover-image uploads need it, and failing here would
        // take down an otherwise working invitation server.
        eprintln!(
            "hainviter: WARNING could not create {}: {e}",
            db::uploads_dir().display()
        );
    }
    db::init(&db::db_path()).expect("failed to open the database");
    println!("hainviter: database ready at {}", db::db_path().display());
    println!("hainviter: audit log at {}", audit::log_path().display());

    let base = std::env::var("HAINVITER_BASE_URL").unwrap_or_default();
    let origin = if base.trim().is_empty() {
        "http://<host>:8080".to_owned()
    } else {
        base.trim_end_matches('/').to_owned()
    };
    println!();
    println!("  ┌────────────────────────────────────────────────────────────");
    println!("  │ HaInviter admin panel — anyone with this link is an admin:");
    println!("  │");
    println!("  │   {origin}/admin/{}", auth::admin_token());
    println!("  │");
    println!("  └────────────────────────────────────────────────────────────");
    println!();

    audit::record(
        "server_started",
        serde_json::json!({
            "version": env!("CARGO_PKG_VERSION"),
            "data_dir": data.display().to_string(),
            "base_url": base,
        }),
    );

    let addr = dioxus::cli_config::fullstack_address_or_localhost();
    let router = axum::Router::new()
        // Uploaded cover images, served straight off the data volume.
        .route("/uploads/{name}", get(serve_upload))
        // CSV download. A plain GET (rather than a server function) so the
        // browser saves a properly named file.
        .route(
            "/admin/{token}/events/{event_id}/responses.csv",
            get(export_csv),
        )
        .serve_dioxus_application(ServeConfig::new(), App)
        .into_make_service();
    let listener = tokio::net::TcpListener::bind(addr)
        .await
        .unwrap_or_else(|e| panic!("cannot bind {addr}: {e}"));
    println!("hainviter: listening on http://{addr}");
    axum::serve(listener, router).await.unwrap();
}

/// Serves one uploaded cover image.
#[cfg(feature = "server")]
async fn serve_upload(
    axum::extract::Path(name): axum::extract::Path<String>,
) -> axum::response::Response {
    use axum::{
        http::{StatusCode, header},
        response::IntoResponse,
    };

    // Stored names are generated by us and are always `<32 hex>.<ext>`; anything
    // else is either a mistake or an attempt to walk out of the directory.
    let valid = !name.is_empty()
        && name.len() <= 64
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_')
        && !name.contains("..");
    if !valid {
        return (StatusCode::BAD_REQUEST, "bad file name").into_response();
    }

    let mime = match name.rsplit_once('.').map(|(_, e)| e) {
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        _ => return (StatusCode::BAD_REQUEST, "unsupported file type").into_response(),
    };

    match tokio::fs::read(db::uploads_dir().join(&name)).await {
        Ok(bytes) => (
            [
                (header::CONTENT_TYPE, mime),
                // File names are random, so a stored image never changes.
                (header::CACHE_CONTROL, "public, max-age=31536000, immutable"),
            ],
            bytes,
        )
            .into_response(),
        Err(_) => (StatusCode::NOT_FOUND, "not found").into_response(),
    }
}

/// Streams an event's responses as a CSV attachment.
#[cfg(feature = "server")]
async fn export_csv(
    axum::extract::Path((token, event_id)): axum::extract::Path<(String, i64)>,
) -> axum::response::Response {
    use axum::{
        http::{StatusCode, header},
        response::IntoResponse,
    };

    if !auth::is_admin(&token) {
        // 404 rather than 403: an invalid admin link should not confirm that the
        // route exists.
        return (StatusCode::NOT_FOUND, "not found").into_response();
    }

    let view = match db::with_db(move |c| db::event_admin_view(c, event_id)).await {
        Ok(Some(v)) => v,
        Ok(None) => return (StatusCode::NOT_FOUND, "no such event").into_response(),
        Err(e) => {
            eprintln!("export: {e}");
            return (StatusCode::INTERNAL_SERVER_ERROR, "export failed").into_response();
        }
    };

    let base = std::env::var("HAINVITER_BASE_URL").unwrap_or_default();
    let body = export::responses_csv(&view.guests, &base);
    let filename = format!("{}-responses.csv", export::slug(&view.event.title));
    audit::record(
        "responses_exported",
        serde_json::json!({ "event_id": event_id, "guests": view.guests.len() }),
    );

    (
        [
            (header::CONTENT_TYPE, "text/csv; charset=utf-8".to_owned()),
            (
                header::CONTENT_DISPOSITION,
                format!("attachment; filename=\"{filename}\""),
            ),
        ],
        body,
    )
        .into_response()
}

// ---------------------------------------------------------------------------
// Client entry point
// ---------------------------------------------------------------------------

#[cfg(not(feature = "server"))]
fn main() {
    dioxus::launch(App);
}
